// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCksA9tr18xdL_Yq9vv0PtMy9NsAOAb9yQ',
    appId: '1:773328857906:web:2f20e88fb6b4ad5650c52b',
    messagingSenderId: '773328857906',
    projectId: 'final-nuntius',
    authDomain: 'final-nuntius.firebaseapp.com',
    storageBucket: 'final-nuntius.appspot.com',
    measurementId: 'G-90L108JGPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDgB_ETe9r7BF96MLzEgxk8S1zggGGofo',
    appId: '1:773328857906:android:31c389382410612a50c52b',
    messagingSenderId: '773328857906',
    projectId: 'final-nuntius',
    storageBucket: 'final-nuntius.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXfP4LIrOmBbX9ZtizSGwNfvin-9mS7UE',
    appId: '1:773328857906:ios:b5608218a1f88bf650c52b',
    messagingSenderId: '773328857906',
    projectId: 'final-nuntius',
    storageBucket: 'final-nuntius.appspot.com',
    iosClientId:
        '773328857906-64uge52jt28cjmttcrg6s94ro1lt17tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalNuntius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXfP4LIrOmBbX9ZtizSGwNfvin-9mS7UE',
    appId: '1:773328857906:ios:4c957bdf9682233f50c52b',
    messagingSenderId: '773328857906',
    projectId: 'final-nuntius',
    storageBucket: 'final-nuntius.appspot.com',
    iosClientId:
        '773328857906-uvbgt1nuhp2upfe5kmt0n6rortovc2tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalNuntius.RunnerTests',
  );
}
